os: Ubuntu2004
platform:
  - x64
install:
  - sudo apt update && sudo apt install --allow-unauthenticated -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils ruby-dev libvirt-dev
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
  - sudo dpkg -i vagrant_2.2.9_x86_64.deb
  - sudo vagrant plugin install vagrant-libvirt vagrant-scp vagrant-reload vagrant-vbguest
  - git submodule init
  - git submodule update
build_script:
  - cp -v salt/roots/pillar/binddns.sls.example salt/roots/pillar/binddns.sls
  - cp -v salt/roots/pillar/filebeat.sls.example salt/roots/pillar/filebeat.sls
  - cp -v salt/roots/pillar/zabbix-agent.sls.example salt/roots/pillar/zabbix-agent.sls
  - cp -v salt/roots/formulas/binddns-formula/binddns/files/zones.conf.example salt/roots/formulas/binddns-formula/binddns/files/zones.conf
  - cp -v salt/roots/formulas/binddns-formula/binddns/files/zones/mynet.zone.example salt/roots/formulas/binddns-formula/binddns/files/zones/mynet.zone
  - cp -v vagrant/examples/binddns/Vagrantfile.binddns-box.fedora-32.x86_64.example vagrant/Vagrantfile.binddns-box
  - cp -v vagrant/examples/server01/Vagrantfile.server01-box.fedora-32.x86_64.example vagrant/Vagrantfile.server01-box
  - cp -v vagrant/examples/server02/Vagrantfile.server02-box.fedora-32.x86_64.example vagrant/Vagrantfile.server02-box
  - cp -v vagrant/examples/tester/Vagrantfile.tester-box.fedora-32.x86_64.example vagrant/Vagrantfile.tester-box
  - sudo vagrant up --provider=libvirt binddns-box
  - sudo vagrant ssh binddns-box -- sudo salt-call state.sls binddns
  - sudo vagrant destroy --force binddns-box
  - sudo vagrant up --provider=libvirt server01-box
  - sudo vagrant destroy --force server01-box
  - sudo vagrant up --provider=libvirt server02-box
  - sudo vagrant destroy --force server02-box
  - sudo vagrant up --provider=libvirt tester-box
  - sudo vagrant destroy --force tester-box
on_success:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh
  - sudo bash install.sh
  - nvm install lts/*
  - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/exec @commitlint/cli @commitlint/config-conventional
  - npx semantic-release
test: off
